[package]
name = "ipkvm-desktop-iced"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
arboard.workspace = true
async-stream = "0.3"
futures-util = { workspace = true }
iced = { version = "0.14", features = ["tokio", "image", "advanced"] }
iced_aw.workspace = true
iced_futures = "0.14"
ipkvm-core = { path = "../ipkvm-core", features = ["serial"] }
ipkvm-desktop = { path = "../ipkvm-desktop" }
ipkvm-session = { path = "../ipkvm-session" }
ipkvm-video = { path = "../ipkvm-video", features = ["mock", "mf"] }
rust-i18n = "4.2.1"
sys-locale = "0.3.2"

[dev-dependencies]
iced_test = "0.14"
iced_runtime = "0.14"
iced_tiny_skia = { version = "0.14", default-features = false }
ipkvm-video = { path = "../ipkvm-video", features = ["mock"] }
tiny-skia = "0.11"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.61", default-features = false, features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_UI_HiDpi",
    "Win32_System_LibraryLoader",
    "Win32_UI_Input",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
] }
rfd = { version = "0.15.4", default-features = false, features = ["common-controls-v6"] }

[[bin]]
name = "ipkvm-desktop-iced"
path = "src/main.rs"

[lib]
name = "ipkvm_desktop_iced"
path = "src/lib.rs"

[build-dependencies]
embed-resource = "3.0.11"

[[example]]
name = "video_1080p"
path = "examples/video_1080p.rs"
