name: CI

on:
  push:
  pull_request:

jobs:
  rust:
    runs-on: ubuntu-latest
    env:
      RUSTUP_DIST_SERVER: https://mirrors.tuna.tsinghua.edu.cn/rustup
      RUSTUP_UPDATE_ROOT: https://mirrors.tuna.tsinghua.edu.cn/rustup/rustup
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.89.0
        with:
          components: rustfmt, clippy
      - name: Check formatting
        run: cargo fmt --all --check
      - name: Run tests
        run: cargo test --workspace --all-features
      - name: Run Clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
