#!/usr/bin/env python3
"""构建发布包：收集 release 二进制、第三方依赖清单、说明文件并压缩。

供 CI 发布 workflow（dev-release / release）调用，在构建完 release
二进制后执行。产物命名：ipkvm-<version>-<os>-<arch>.zip|.tar.gz。
架构默认按运行平台自动检测（x86_64/aarch64），可用 --arch 显式覆盖。

用法：
    python build-release-package.py --os Windows --version dev --out dist
    python3 build-release-package.py --os Linux --version v0.2.0 --out dist
"""

from __future__ import annotations

import argparse
import json
import platform
import shutil
import subprocess
import sys
import tarfile
import zipfile
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# runner 平台 → 发布包架构标注（macos-latest 为 Apple Silicon，#118）
ARCH_BY_MACHINE = {
    "AMD64": "x86_64",
    "x86_64": "x86_64",
    "arm64": "aarch64",
    "aarch64": "aarch64",
}

# 用户可用发布产物：(crate, bin 名)。browser-fixture 是测试工具，不发版。
BINARIES = {
    "ipkvm-headless": ("ipkvm-headless-app", "ipkvm-headless"),
    "ipkvm-desktop-iced": ("ipkvm-desktop-iced", "ipkvm-desktop-iced"),
}


def run(cmd, **kwargs):
    # Windows 上 text=True 默认用 locale 编码（cp1252），cargo metadata 的
    # UTF-8 输出含非 ASCII 描述会解码失败，必须显式指定 UTF-8。
    return subprocess.run(
        cmd,
        check=True,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        **kwargs,
    )


def collect_third_party_licenses(staging: Path, commit: str) -> None:
    """从 cargo metadata 生成第三方依赖清单（名称、版本、许可证、来源）。"""
    meta = run(["cargo", "metadata", "--format-version", "1"], cwd=REPO_ROOT)
    packages = json.loads(meta.stdout)["packages"]
    repo_prefix = str(REPO_ROOT).replace("\\", "/")
    lines = [
        "# Third-party dependencies (generated by CI from `cargo metadata`)",
        f"# commit: {commit}",
        "",
        "name,version,license,repository,workspace-member",
    ]
    for package in sorted(packages, key=lambda p: p["name"].lower()):
        license_expr = package.get("license") or package.get("license_file") or "(none)"
        is_member = package["manifest_path"].replace("\\", "/").startswith(repo_prefix)
        lines.append(
            f'{package["name"]},{package["version"]},"{license_expr}",'
            f'{package.get("repository") or ""},{is_member}'
        )
    (staging / "THIRD_PARTY_LICENSES.txt").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--os", required=True, choices=["Windows", "Linux", "macOS"])
    parser.add_argument("--version", required=True, help="dev 或 v0.2.0")
    parser.add_argument(
        "--arch",
        choices=sorted(set(ARCH_BY_MACHINE.values())),
        default=None,
        help="目标架构；默认按当前平台自动检测",
    )
    parser.add_argument("--out", default="dist", help="输出目录（默认 dist）")
    args = parser.parse_args()

    is_windows = args.os == "Windows"
    exe = ".exe" if is_windows else ""
    machine = platform.machine()
    arch = args.arch or ARCH_BY_MACHINE.get(machine)
    if arch is None:
        print(f"Error: cannot detect arch from platform.machine()={machine!r}; pass --arch", file=sys.stderr)
        return 1

    release_dir = REPO_ROOT / "target" / "release"
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    # commit 与日期（写入说明文件）
    commit = run(["git", "rev-parse", "HEAD"], cwd=REPO_ROOT).stdout.strip()
    short_commit = commit[:8]
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    # 第三方依赖清单（所有包共用）
    licenses_content = None

    # 为每个可执行文件单独打包
    for bin_name in BINARIES:
        src = release_dir / f"{bin_name}{exe}"
        if not src.exists():
            print(f"Error: missing release binary: {src}", file=sys.stderr)
            return 1

        pkg_name = f"{bin_name}-{args.version}-{args.os.lower()}-{arch}"
        staging = out_dir / f"stage-{bin_name}"
        if staging.exists():
            shutil.rmtree(staging)
        staging.mkdir(parents=True)

        # 1. 收集 release 二进制
        shutil.copy2(src, staging / f"{bin_name}{exe}")

        # 2. 第三方依赖清单
        if licenses_content is None:
            collect_third_party_licenses(staging, commit)
            licenses_content = (staging / "THIRD_PARTY_LICENSES.txt").read_text(encoding="utf-8")
        else:
            (staging / "THIRD_PARTY_LICENSES.txt").write_text(licenses_content, encoding="utf-8")

        # 3. 说明文件与许可证
        readme_template = (REPO_ROOT / "release" / "package-readme.md").read_text(
            encoding="utf-8"
        )
        readme = (
            readme_template.replace("{version}", args.version)
            .replace("{commit}", short_commit)
            .replace("{date}", date)
            .replace("{binary}", bin_name)
        )
        (staging / "README.txt").write_text(readme, encoding="utf-8")
        shutil.copy2(REPO_ROOT / "LICENSE", staging / "LICENSE")

        # 4. 压缩
        files = sorted(f for f in staging.rglob("*") if f.is_file())
        if is_windows:
            out_path = out_dir / f"{pkg_name}.zip"
            with zipfile.ZipFile(out_path, "w", zipfile.ZIP_DEFLATED) as archive:
                for f in files:
                    archive.write(f, f.relative_to(staging))
        else:
            out_path = out_dir / f"{pkg_name}.tar.gz"
            with tarfile.open(out_path, "w:gz") as archive:
                for f in files:
                    archive.add(f, arcname=f.relative_to(staging))

        shutil.rmtree(staging)
        print(out_path.resolve())

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
