#!/usr/bin/env python3
"""构建发布包：收集 release 二进制、第三方依赖清单、说明文件并压缩。

供 CI 发布 workflow（dev-release / release）调用，在构建完 release
二进制后执行。产物命名：ipkvm-<version>-<os>-<arch>.zip|.tar.gz。

用法：
    python build-release-package.py --os Windows --version dev --out dist
    python3 build-release-package.py --os Linux --version v0.2.0 --out dist
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tarfile
import zipfile
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# 用户可用发布产物：(crate, bin 名)。browser-fixture 是测试工具，不发版。
BINARIES = {
    "ipkvm-headless": ("ipkvm-headless-app", "ipkvm-headless"),
    "ipkvm-demo": ("ipkvm-headless-demo", "ipkvm-demo"),
    "ipkvm-desktop-iced": ("ipkvm-desktop-iced", "ipkvm-desktop-iced"),
}


def run(cmd, **kwargs):
    # Windows 上 text=True 默认用 locale 编码（cp1252），cargo metadata 的
    # UTF-8 输出含非 ASCII 描述会解码失败，必须显式指定 UTF-8。
    return subprocess.run(
        cmd,
        check=True,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        **kwargs,
    )


def collect_third_party_licenses(staging: Path, commit: str) -> None:
    """从 cargo metadata 生成第三方依赖清单（名称、版本、许可证、来源）。"""
    meta = run(["cargo", "metadata", "--format-version", "1"], cwd=REPO_ROOT)
    packages = json.loads(meta.stdout)["packages"]
    repo_prefix = str(REPO_ROOT).replace("\\", "/")
    lines = [
        "# Third-party dependencies (generated by CI from `cargo metadata`)",
        f"# commit: {commit}",
        "",
        "name,version,license,repository,workspace-member",
    ]
    for package in sorted(packages, key=lambda p: p["name"].lower()):
        license_expr = package.get("license") or package.get("license_file") or "(none)"
        is_member = package["manifest_path"].replace("\\", "/").startswith(repo_prefix)
        lines.append(
            f'{package["name"]},{package["version"]},"{license_expr}",'
            f'{package.get("repository") or ""},{is_member}'
        )
    (staging / "THIRD_PARTY_LICENSES.txt").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--os", required=True, choices=["Windows", "Linux", "macOS"])
    parser.add_argument("--version", required=True, help="dev 或 v0.2.0")
    parser.add_argument("--out", default="dist", help="输出目录（默认 dist）")
    args = parser.parse_args()

    is_windows = args.os == "Windows"
    exe = ".exe" if is_windows else ""
    arch = "x86_64"

    release_dir = REPO_ROOT / "target" / "release"
    pkg_name = f"ipkvm-{args.version}-{args.os.lower()}-{arch}"
    out_dir = Path(args.out)
    staging = out_dir / "stage"
    if staging.exists():
        shutil.rmtree(staging)
    bin_dir = staging / "bin"
    bin_dir.mkdir(parents=True)

    # 1. 收集 release 二进制
    for bin_name in BINARIES:
        src = release_dir / f"{bin_name}{exe}"
        if not src.exists():
            print(f"Error: missing release binary: {src}", file=sys.stderr)
            return 1
        shutil.copy2(src, bin_dir / f"{bin_name}{exe}")

    # 2. commit 与日期（写入说明文件）
    commit = run(["git", "rev-parse", "HEAD"], cwd=REPO_ROOT).stdout.strip()
    short_commit = commit[:8]
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    # 3. 第三方依赖清单
    collect_third_party_licenses(staging, commit)

    # 4. 说明文件与许可证
    readme_template = (REPO_ROOT / "release" / "package-readme.md").read_text(
        encoding="utf-8"
    )
    readme = (
        readme_template.replace("{version}", args.version)
        .replace("{commit}", short_commit)
        .replace("{date}", date)
    )
    (staging / "README.txt").write_text(readme, encoding="utf-8")
    shutil.copy2(REPO_ROOT / "LICENSE", staging / "LICENSE")

    # 5. 压缩
    out_dir.mkdir(parents=True, exist_ok=True)
    files = sorted(f for f in staging.rglob("*") if f.is_file())
    if is_windows:
        out_path = out_dir / f"{pkg_name}.zip"
        with zipfile.ZipFile(out_path, "w", zipfile.ZIP_DEFLATED) as archive:
            for f in files:
                archive.write(f, f.relative_to(staging))
    else:
        out_path = out_dir / f"{pkg_name}.tar.gz"
        with tarfile.open(out_path, "w:gz") as archive:
            for f in files:
                archive.add(f, arcname=f.relative_to(staging))

    print(out_path.resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
