[package]
name = "ipkvm-desktop"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
arboard.workspace = true
ipkvm-core = { path = "../ipkvm-core", features = ["serial"] }
ipkvm-device = { path = "../ipkvm-device", features = ["platform"] }
ipkvm-desktop-core = { path = "../ipkvm-desktop-core" }
ipkvm-rfb = { path = "../ipkvm-rfb" }
ipkvm-session = { path = "../ipkvm-session" }
ipkvm-video = { path = "../ipkvm-video", features = ["camera"] }
jpeg-encoder.workspace = true
serialport.workspace = true
thiserror.workspace = true
