[package]
name = "ipkvm-desktop"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
arboard.workspace = true
ipkvm-core = { path = "../ipkvm-core", features = ["serial"] }
ipkvm-rfb = { path = "../ipkvm-rfb" }
ipkvm-session = { path = "../ipkvm-session", features = ["serial"] }
ipkvm-video = { path = "../ipkvm-video", features = ["mf"] }
jpeg-encoder.workspace = true
serde.workspace = true
serialport.workspace = true
sys-locale = "0.3.2"
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "sync", "time"] }
toml.workspace = true

[dev-dependencies]
ipkvm-video = { path = "../ipkvm-video", features = ["mock"] }

[package.metadata.i18n]
available-locales = ["zh-CN", "en"]
default-locale = "zh-CN"
load-path = "locales"
